# Generated by Django 4.2.7 on 2023-11-26 12:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NGSDataPath',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_path', models.CharField(max_length=332, verbose_name='data path')),
                ('data_name', models.CharField(max_length=332, verbose_name='data name')),
                ('data_type', models.CharField(blank=True, max_length=332, null=True, verbose_name='data type')),
                ('create_time', models.DateField(db_index=True, verbose_name='create time')),
                ('status', models.CharField(max_length=332, verbose_name='status')),
            ],
        ),
        migrations.CreateModel(
            name='Tools',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tools_name', models.CharField(max_length=64, verbose_name='小工具')),
                ('tools_id', models.CharField(max_length=64, verbose_name='tools_id')),
                ('tools_desc', models.TextField(verbose_name='功能表述')),
                ('tools_icon', models.ImageField(blank=True, upload_to='static/img/tools_icon')),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tools_name', models.CharField(choices=[('RBC', 'rbc'), ('HLA', 'hla'), ('HPA', 'hpa')], max_length=10, verbose_name='tool name')),
                ('unique_id', models.CharField(max_length=255, unique=True, verbose_name='unique id')),
                ('proj_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='proj name')),
                ('result_path', models.CharField(blank=True, max_length=255, null=True, verbose_name='resu path')),
                ('raw_data', models.CharField(blank=True, max_length=255, null=True, verbose_name='raw data')),
                ('status', models.CharField(default='pending', max_length=20, verbose_name='status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='start time')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='finish time')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
