# Generated by Django 4.2.7 on 2023-11-03 05:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tools.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tools',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tools_name', models.CharField(max_length=64, verbose_name='小工具')),
                ('tools_id', models.CharField(max_length=64, verbose_name='tools_id')),
                ('tools_desc', models.TextField(verbose_name='功能表述')),
                ('tools_icon', models.ImageField(blank=True, upload_to='static/img/tools_icon')),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tools_name', models.CharField(choices=[('RBC', 'rbc'), ('HLA', 'hla'), ('HPA', 'hpa')], max_length=10)),
                ('unique_id', models.CharField(max_length=255, unique=True)),
                ('project_name', models.CharField(blank=True, max_length=255, null=True)),
                ('result_path', models.CharField(blank=True, max_length=255, null=True)),
                ('data', models.FileField(max_length=255, upload_to=tools.models.generate_upload_path, verbose_name='data')),
                ('status', models.CharField(default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
