# Generated by Django 4.1 on 2024-01-13 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tools", "0003_remove_result_fq_count_remove_result_fq_gz_count_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="RBCPanel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="panel name")),
                (
                    "panel_file",
                    models.FileField(
                        upload_to="static/files/rbc_panel", verbose_name="panel file"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="create time"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="update time"),
                ),
            ],
        ),
    ]
